kafka-manager:
  image: sheepkiller/kafka-manager
  external_links:
  - zookeeper_zookeeper-3_1:zookeeper-3
  - zookeeper_zookeeper-2_1:zookeeper-2
  - zookeeper_zookeeper-1_1:zookeeper-1
  ports:
  - "9000:9000"
  environment:
  - ZK_HOSTS=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
  - APPLICATION_SECRET=letmein

kafka:
  image: zenviavas/kafka
  expose:
  - "9092"
  - "8005"
  external_links:
  - zookeeper_zookeeper-3_1:zookeeper-3
  - zookeeper_zookeeper-2_1:zookeeper-2
  - zookeeper_zookeeper-1_1:zookeeper-1
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  environment:
    JMX_PORT: 8005 # the kafka image can dynamically reasing the JMX port to an external port, just need to set
    # JMX_EXPOSE: true
    KAFKA_CREATE_TOPICS: info:1:1,warn:1:1,debug:1:1,error:1:1 # when scalling kafka needs to reasing the partitions to use all nodes on cluster
    KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
    KAFKA_ADVERTISED_PORT: 9092 # unset this variable if wants to dinamically expose to outside the container net
    HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $$1}'"
    #HOSTNAME_COMMAND: route -n | awk '/UG[ \t]/{print $$2}' in case its needed to expose to outside the container
    # also set the ports above to be mapped to outised the container net
