# The admin tools use the load balancer in order to allow dynamic cluster scale
kibana:
  image: kibana:4.4
  links:
    - es-client-balancer
  ports:
  - 5601:5601
  environment:
    ELASTICSEARCH_URL: "http://es-client-balancer:9200"
kopf:
  image: lmenezes/elasticsearch-kopf
  links:
    - es-client-balancer
  ports:
  - 8888:80
  environment:
  - KOPF_SERVER_NAME=zenvia
  - KOPF_ES_SERVERS=es-client-balancer:9200

es-client-balancer:
  image: tutum/haproxy
  ports:
    - "9200:9200"
    - "1936:1936"
  links:
    - elasticsearch-client

# The client and data nodes can be dinamically scaled up and down.

# when scalling the client nodes, need to reload the load balancer node
elasticsearch-client:
  image: zenviavas/elasticsearch
  links:
  - elasticsearch-master
  expose:
  - "9200"
  environment:
  - CLUSTER=zenvia
  - CLIENT_NODE=true
  - UNICAST_HOSTS=elasticsearch-master
  - TCP_PORTS=9200

# The data node is a master eligle node as well
elasticsearch-data:
  image: zenviavas/elasticsearch
  links:
  - elasticsearch-master
  environment:
  - CLUSTER=zenvia
  - DATA_NODE=true
  - UNICAST_HOSTS=elasticsearch-master
elasticsearch-master:
  image: zenviavas/elasticsearch
  environment:
  - CLUSTER=zenvia
  - MASTER_NODE=true
