# TODO find a zookeeper manager tool like exhibitor
zookeeper-maestro:
  image: zenviavas/zookeeper-maestro
  volumes_from:
  - zookeeper-1
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  links:
  - zookeeper-3
  - zookeeper-2
  - zookeeper-1
zookeeper-3:
  image: zenviavas/zookeeper
  volumes_from:
  - zookeeper-1
  environment:
  - ZOO_ID=3
  expose:
  - "2181"
  - "2888"
  - "3888"
  labels:
  -  "zookeeper.server"
zookeeper-2:
  image: zenviavas/zookeeper
  volumes_from:
  - zookeeper-1
  environment:
  - ZOO_ID=2
  expose:
  - "2181"
  - "2888"
  - "3888"
  labels:
  -  "zookeeper.server"
zookeeper-1:
  image: zenviavas/zookeeper
  volumes:
  - /zookeeper/conf
  environment:
  - ZOO_ID=1
  expose:
  - "2181"
  - "2888"
  - "3888"
  labels:
  -  "zookeeper.server"
