fluentdprocessor:
  image: zenviavas/fluentd
  links:
  - zookeeper-3
  - zookeeper-2
  - zookeeper-1
  #TODO: work on the posseidon fork in order to allow the brokers auto discovery in order to make it scalable
  - kafka
  - es-client-balancer:elasticsearch
  environment:
  - FLUENTD_CONFIG=kafka2es
fluentdreceiver:
  image: zenviavas/fluentd
  links:
  - zookeeper-3
  - zookeeper-2
  - zookeeper-1
  ports:
  - "9880:9880"
  environment:
  - FLUENTD_CONFIG=app2kafka

################################################################################
# Kafka - docker-compose-kaf
################################################################################
kafka-manager:
  image: sheepkiller/kafka-manager
  links:
  - zookeeper-3
  - zookeeper-2
  - zookeeper-1
  ports:
  - "9000:9000"
  environment:
  - ZK_HOSTS=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
  - APPLICATION_SECRET=letmein
kafka:
  image: zenviavas/kafka
  expose:
  - "9092"
  - "8005"
  links:
  - zookeeper-3
  - zookeeper-2
  - zookeeper-1
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  environment:
    JMX_PORT: 8005
    KAFKA_CREATE_TOPICS: info:1:1,warn:1:1,debug:1:1,error:1:1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
    KAFKA_ADVERTISED_PORT: 9092
    HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $$1}'"
################################################################################

################################################################################
# Zookeeper
################################################################################
zookeeper-maestro:
  image: zenviavas/zookeeper-maestro
  volumes_from:
  - zookeeper-1
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  links:
  - zookeeper-3
  - zookeeper-2
  - zookeeper-1
zookeeper-3:
  image: zenviavas/zookeeper
  volumes_from:
  - zookeeper-1
  environment:
  - ZOO_ID=3
  expose:
  - "2181"
  - "2888"
  - "3888"
  labels:
  -  "zookeeper.server"
zookeeper-2:
  image: zenviavas/zookeeper
  volumes_from:
  - zookeeper-1
  environment:
  - ZOO_ID=2
  expose:
  - "2181"
  - "2888"
  - "3888"
  labels:
  -  "zookeeper.server"
zookeeper-1:
  image: zenviavas/zookeeper
  volumes:
  - /zookeeper/conf
  environment:
  - ZOO_ID=1
  expose:
  - "2181"
  - "2888"
  - "3888"
  labels:
  -  "zookeeper.server"
################################################################################

################################################################################
# Elasticsearch + kibana
################################################################################
kibana:
  image: kibana:4.4
  links:
    - es-client-balancer
  ports:
  - 5601:5601
  environment:
    ELASTICSEARCH_URL: "http://es-client-balancer:9200"
kopf:
  image: lmenezes/elasticsearch-kopf
  links:
    - es-client-balancer
  ports:
  - 8888:80
  environment:
  - KOPF_SERVER_NAME=zenvia
  - KOPF_ES_SERVERS=es-client-balancer:9200

es-client-balancer:
  image: tutum/haproxy
  ports:
    - "9200:9200"
    - "1936:1936"
  links:
    - elasticsearch-client

elasticsearch-client:
  image: zenviavas/elasticsearch
  links:
  - elasticsearch-master
  expose:
  - "9200"
  environment:
  - CLUSTER=zenvia
  - CLIENT_NODE=true
  - UNICAST_HOSTS=elasticsearch-master
  - TCP_PORTS=9200
elasticsearch-data:
  image: zenviavas/elasticsearch
  links:
  - elasticsearch-master
  environment:
  - CLUSTER=zenvia
  - DATA_NODE=true
  - UNICAST_HOSTS=elasticsearch-master
elasticsearch-master:
  image: zenviavas/elasticsearch
  environment:
  - CLUSTER=zenvia
  - MASTER_NODE=true
################################################################################
