kafka-manager:
  image: sheepkiller/kafka-manager
  external_links:
  - zookeeper/zookeeper:zookeeper
  ports:
  - "9000:9000"
  environment:
  - ZK_HOSTS=zookeeper:2181
  - APPLICATION_SECRET=letmein

kafka-conf:
  image: zenviavas/kafka-conf
  volumes_from:
    - kafka
  net: "container:kafka"
kafka:
  image: zenviavas/kafka:0.9
  external_links:
  - zookeeper/zookeeper:zookeeper
  volumes:
  - /opt/kafka/conf.d
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.sidekicks: kafka-conf
  environment:
    #KAFKA_CREATE_TOPICS: info:1:1,debug:1:1,warn:1:1,error:1:1
    KAFKA_CONFIG_LOG_DIRS: /data/kafka
    JMX_PORT: 8500
    KAFKA_CONFIG_ZOOKEEPER_CONNECT: zookeeper:2181
